list:
  demo:
    values: A,B,C,D,E,F,G
map:
  demo:
    values: '{A:"alpha", B:"beta", G:"gamma"}'

mail:
  server:
    url: http://url-config-server
    port: 900
    userName: dummy
    password: pass

