list:
  demo:
    values: A,B,C,D,E,F,G
map:
  demo:
    values: '{A:"alpha", B:"beta", G:"gamma"}'

mail:
  server:
    url: http://testUrl
    port: 900
    userName: dummy
    password: pass
    
management:
  endpoints:
    web:
      exposure:
        include: configprops
